### ISSUE TITLE
Getting Some Kind of Error

### ISSUE THREAD

**Issue by AbirHasan2005** [Mahesh0253/Media-Search-bot#20]
Please Help to solve this error:
```
2021-02-05T08:12:23.841256+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-05T08:12:23.841280+00:00 app[worker.1]:   File "bot.py", line 12, in <module>
2021-02-05T08:12:23.841355+00:00 app[worker.1]:     from utils import Media
2021-02-05T08:12:23.841371+00:00 app[worker.1]:   File "/app/utils.py", line 13, in <module>
2021-02-05T08:12:23.841462+00:00 app[worker.1]:     instance = Instance(db)
2021-02-05T08:12:23.841483+00:00 app[worker.1]: TypeError: Can't instantiate abstract class Instance with abstract methods is_compatible_with
```

**Comment by Mahesh0253** [comment]
Run following commands

`pip3 install -U motor==2.3.0`
`pip3 install -U umongo==2.3.0`
