### ISSUE TITLE
INDEX COMMAND ERROR

### ISSUE THREAD

**Issue by ianwaithaka** [Mahesh0253/Media-Search-bot#34]
when i run /index command I'M GETTING THIS **Error: unpack requires a buffer of 263 bytes** 
here are the heroku logs

2021-07-01T08:11:31.272699+00:00 app[worker.1]: Qtagbot with for Pyrogram v1.2.9 (Layer 128) started on qtagbot.
2021-07-01T08:14:02.330614+00:00 app[worker.1]: 08:14:02 AM - 61 - plugins.userbot - userbot - ERROR - unpack requires a buffer of 263 bytes
2021-07-01T08:14:02.330623+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-01T08:14:02.330625+00:00 app[worker.1]:   File "/app/plugins/userbot.py", line 32, in index_files
2021-07-01T08:14:02.330626+00:00 app[worker.1]:     async with user_bot:
2021-07-01T08:14:02.330627+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client.py", line 258, in __aenter__
2021-07-01T08:14:02.330627+00:00 app[worker.1]:     return await self.start()
2021-07-01T08:14:02.330628+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 53, in start
2021-07-01T08:14:02.330628+00:00 app[worker.1]:     is_authorized = await self.connect()
2021-07-01T08:14:02.330628+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
2021-07-01T08:14:02.330629+00:00 app[worker.1]:     await self.load_session()
2021-07-01T08:14:02.330629+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/client.py", line 672, in load_session
2021-07-01T08:14:02.330630+00:00 app[worker.1]:     await self.storage.open()
2021-07-01T08:14:02.330630+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/storage/memory_storage.py", line 38, in open
2021-07-01T08:14:02.330631+00:00 app[worker.1]:     dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
2021-07-01T08:14:02.330631+00:00 app[worker.1]: struct.error: unpack requires a buffer of 263 bytes

**Comment by Mahesh0253** [comment]
Create new user bot session string then try again

**Comment by ianwaithaka** [comment]
oh thanks it worked

**Comment by ianwaithaka** [comment]
oh thanks it worked
